### ISSUE TITLE
搜索功能用不了

### ISSUE THREAD

**Issue by zhangliukun** [stkevintan/hexo-theme-material-flow#1]
在 安装依赖以后，运行hexo g的时候有下面异常，不影响使用，但不知搜索不能用是不是和这个有关
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }

**Comment by stkevintan** [comment]
文档的失误，还需要安装`hexo-generator-json-content`
你的错误貌似与问题无关：<https://hexo.io/docs/troubleshooting.html#Error-with-DTrace-Mac-OS-X>

**Comment by zhangliukun** [comment]
可以了👍
