### ISSUE TITLE
目录太多导致显示不下

### ISSUE THREAD

**Issue by zhangliukun** [stkevintan/hexo-theme-material-flow#13]
查看文章的时候又变目录如果很多的话超过屏幕部分就被挡住了，希望能够让目录可以滑动。
另外，现在的 markdown 中表格的样式是没有的，建议添加一下表格的样式，👍

**Comment by stkevintan** [comment]
OK,正在找工作，可能fix比较晚

**Comment by stkevintan** [comment]
fixed
