### ISSUE TITLE
Home page have a url does not support https

### ISSUE THREAD

**Issue by twiceyuan** [stkevintan/hexo-theme-material-flow#14]
http://api.hitokoto.us/rand?length=80&encode=jsc&fun=handlerHitokoto&_=1489808727483

BTW, is there a configure item to disable or custom the text content of this banner?

**Comment by stkevintan** [comment]
yeah， I‘ll correct it.

**Comment by lukaMis** [comment]
I have a pull request waiting with this quote text being optional.
https://github.com/stkevintan/hexo-theme-material-flow/pulls

**Comment by stkevintan** [comment]
I have removed the useless banner. thanks!
