### ISSUE TITLE
Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by jniltinho** [stkevintan/hexo-theme-material-flow#17]
Unhandled rejection TypeError: /home/nilton/Projetos/LinuxPro/hexo_blog/themes/material-flow/layout/layout.ejs:1
 >> 1| <%- partial('_partial/head') %>
    2| <body>
    3|   <%- partial('_partial/loading') %>
    4|   <script>setLoadingBarProgress(20)</script> 

/home/nilton/Projetos/LinuxPro/hexo_blog/themes/material-flow/layout/_partial/head.ejs:22
    20|   <title><% if (title) { %><%= title %> | <% } %><%= config.title %></title>
    21|   <meta name="description" content="<%= config.description %>" />
 >> 22|   <meta name="keywords" content="<%=config.keywords.join(',') %>" />
    23|   <meta name="HandheldFriendly" content="True" />
    24|   <meta name="apple-mobile-web-app-capable" content="yes">
    25|   <%- favicon_tag(config.favicon) %>

Cannot read property 'join' of undefined
    at eval (eval at exports.compile (/home/nilton/Projetos/LinuxPro/hexo_blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:43:388)
    at eval (eval at exports.compile (/home/nilton/Projetos/LinuxPro/hexo_blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:47:1161)
    at /home/nilton/Projetos/LinuxPro/hexo_blog/node_modules/ejs/lib/ejs.js:255:

**Comment by ichennan** [comment]
i have the same problem, is it fixed ?

**Comment by stkevintan** [comment]
maybe you forget add some keywords in your config.yml?

**Comment by stkevintan** [comment]
this bug  has fixed, A little mistake = =

**Comment by jniltinho** [comment]
Add _config.yml

keywords: 
- tutoriais
- howtos
- ubuntu
- centos
- debian
- opensuse

**Comment by jniltinho** [comment]
My Blog/Site
http://www.linuxpro.com.br/
Thanks for your template !!!!

**Comment by jniltinho** [comment]
Your template is wonderful, it's helping me a lot.

**Comment by stkevintan** [comment]
thank you! Nice tweak~
