### ISSUE TITLE
新功能添加

### ISSUE THREAD

**Issue by zhangliukun** [stkevintan/hexo-theme-material-flow#2]
希望能够增加一些个性化配置：
1.Archives 能够配置文章按最新的时间到旧的排序，因为很多文章很旧的话浏览的需求不是那么高。
2.点击 Categories 能够增加一种只显示标题的的配置，因为文章很多的话根据分类找具体文章很麻烦。

作者辛苦了。

**Comment by stkevintan** [comment]
1. 已改
2. 没想好怎么设计

**Comment by zhangliukun** [comment]
好了，material design风格还是很赞的
