### ISSUE TITLE
Theme not working in subdirectory

### ISSUE THREAD

**Issue by lukaMis** [stkevintan/hexo-theme-material-flow#4]
Hi

If i try to set subdirectory in _config.yml like this:

```
url: my_site_url/blog/
root: /blog/
```

Theme does not work correctly. 
Icon fonts are not found, avatar image is missing and search function does not work.
[Example](http://lukamis.com/blog/)
Any ideas how to fix this?

**Comment by stkevintan** [comment]
maybe these'll be fixed in the latest edition~

**Comment by lukaMis** [comment]
@stkevintan 
Latest edition of what? Hexo?
This issue is with this theme. If i put blog in sub-directory with default Hexo theme it works.

**Comment by stkevintan** [comment]
@lukaMis  I means the last edition of my theme that I updated it that day and fixed the bugs of yours.
Sorry for my poor expression..😁

**Comment by lukaMis** [comment]
@stkevintan 
No problem man.
Tnx for quick fix.
