### ISSUE TITLE
滚动图片框为空

### ISSUE THREAD

**Issue by SincerelyUnique** [stkevintan/hexo-theme-material-flow#43]
您好，之前有用您的主题，上面好像有个滚动的图片框，我现在用的时候没有滚动图片了，请问一下是否是下面的那个链接失效了
http://api.hitokoto.us/rand?length=80&encode=jsc&fun=handlerHitokoto
我的地址是：http://jalen.site/

**Comment by UGxhdHlwdXM** [comment]
图片的地址是这个吧
http://s.qdcdn.com/cl/10112088,1280,800.jpg
那个hitokoto是[一言](https://hitokoto.cn/)的

**Comment by SincerelyUnique** [comment]
@PlatypusPro 是的，我的地址贴错了，不过你的这个地址也访问不了，我看程序好像是从lovewallpaper.json里定义的图片地址，好像是爱壁纸这个网站的墙纸，现在这些链接都访问不了了

**Comment by SincerelyUnique** [comment]
改好了，写死了一个url
