### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SincerelyUnique** [stkevintan/hexo-theme-material-flow#6]
$ hexo g
Unhandled rejection TypeError: /hexo/themes/material/layout/layout.ejs:13
    11|       </div>
    12|       <aside class='l_side'>
 >> 13|         <%- partial('_partial/side') %>
    14|       </aside>
    15|       <script>setLoadingBarProgress(60);</script>
    16|     </div>

/hexo/themes/material/layout/_partial/side.ejs:1
 >> 1| <% (site.data.widgets||[]).forEach(function(name){ %>  
    2|   <%- partial('_widget/'+name) %>
    3| <% }) %> 
    4| 

(site.data.widgets || []).forEach is not a function
    at ... ...

This is my side.ejs : 
<% (site.data.widgets||[]).forEach(function(name){ %>  
  <%- partial('_widget/'+name) %>
<% }) %> 

Could you help me check it?

**Comment by stkevintan** [comment]
maybe，the format of your `source/_data/widgets.yml` is wrong. can you paste it's content here?

**Comment by SincerelyUnique** [comment]
OK,here is my content,please have a look:
widgets.yml:
`- about
- friendly-links
- categories
- tagcloud`

**Comment by SincerelyUnique** [comment]
OK,here is my content (widgets.yml):
- about
- friendly-links
- categories
- tagcloud

**Comment by SincerelyUnique** [comment]
Ok,here is my content (widgets.yml):
`
- about
- friendly-links
- categories
- tagcloud
`

**Comment by SincerelyUnique** [comment]
```
- about
- friendly-links
- categories
- tagcloud
```

**Comment by SincerelyUnique** [comment]
Please have a look,thanks!

**Comment by SincerelyUnique** [comment]
![2017-02-20 08 34 37](https://cloud.githubusercontent.com/assets/16249717/23108390/959ac510-f747-11e6-8e4e-f9739db55a50.png)

**Comment by kevinetc123** [comment]
add following code at the begin of your `side.ejs` and paste the output in the webpage
```
<%- site.data.widgets %>
```

**Comment by SincerelyUnique** [comment]
Thanks for your reply,I just solve this problem in this way:
1. Add widgets in "themes/material-flow/_config.yml", like this
```
- about         # See also: `about_content`
- categories
- tagcloud
```
2. Then change "side.ejs" to : 
```
<% theme.widgets.forEach(function(name){ %>
  <%- partial('_widget/'+name) %>
<% }) %>
```

then it works!

**Comment by stkevintan** [comment]
Ok！
